apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-sonarqube-pv
  namespace: sonar-demo
  labels:
    type: sonarqube
spec:
  storageClassName: sonarqube
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /opt/sonarqube
