apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdlee-sonarqube-pvc
  labels:
    type: sonarqube
spec:
  storageClassName: sonarqube
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
