apiVersion: v1
kind: PersistentVolume
metadata:
  name: lab99-postgre-pv
  labels:
    type: postgre
spec:
  storageClassName: postgre
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: "/mnt/postgre"

