apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lab99-postgre-pvc
  labels:
    type: postgre
spec:
  storageClassName: postgre
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
